"""create remaining domain models

Revision ID: 40c4824ddf74
Revises: 5fa5637ea09f
Create Date: 2026-08-22 11:13:11.938081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '40c4824ddf74'
down_revision: Union[str, None] = '5fa5637ea09f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admimsides_id'), table_name='admimsides')
    op.drop_index(op.f('ix_admimsides_is_active'), table_name='admimsides')
    op.drop_index(op.f('ix_admimsides_name'), table_name='admimsides')
    op.drop_table('admimsides')
    op.drop_index(op.f('ix_homes_id'), table_name='homes')
    op.drop_index(op.f('ix_homes_is_active'), table_name='homes')
    op.drop_index(op.f('ix_homes_name'), table_name='homes')
    op.drop_table('homes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('homes_pkey'))
    )
    op.create_index(op.f('ix_homes_name'), 'homes', ['name'], unique=False)
    op.create_index(op.f('ix_homes_is_active'), 'homes', ['is_active'], unique=False)
    op.create_index(op.f('ix_homes_id'), 'homes', ['id'], unique=False)
    op.create_table('admimsides',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('admimsides_pkey'))
    )
    op.create_index(op.f('ix_admimsides_name'), 'admimsides', ['name'], unique=False)
    op.create_index(op.f('ix_admimsides_is_active'), 'admimsides', ['is_active'], unique=False)
    op.create_index(op.f('ix_admimsides_id'), 'admimsides', ['id'], unique=False)
    # ### end Alembic commands ###
