"""create auth tables

Revision ID: 5fa5637ea09f
Revises: 
Create Date: 2026-08-22 10:44:45.748881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5fa5637ea09f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admimsides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admimsides_id'), 'admimsides', ['id'], unique=False)
    op.create_index(op.f('ix_admimsides_is_active'), 'admimsides', ['is_active'], unique=False)
    op.create_index(op.f('ix_admimsides_name'), 'admimsides', ['name'], unique=False)
    op.create_table('homes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homes_id'), 'homes', ['id'], unique=False)
    op.create_index(op.f('ix_homes_is_active'), 'homes', ['is_active'], unique=False)
    op.create_index(op.f('ix_homes_name'), 'homes', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_homes_name'), table_name='homes')
    op.drop_index(op.f('ix_homes_is_active'), table_name='homes')
    op.drop_index(op.f('ix_homes_id'), table_name='homes')
    op.drop_table('homes')
    op.drop_index(op.f('ix_admimsides_name'), table_name='admimsides')
    op.drop_index(op.f('ix_admimsides_is_active'), table_name='admimsides')
    op.drop_index(op.f('ix_admimsides_id'), table_name='admimsides')
    op.drop_table('admimsides')
    # ### end Alembic commands ###
